### PR TITLE
Move type annotations inline

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by jribbens** [comment]
My personal opinion is that removing compatibility with older versions of Python for the sake of it is a bit pointless. Replacing the `.format` strings with `f` strings instead offers no noticeable benefit, for example. And I think I'm right in saying that the function type annotations would work fine under Python 3.5 anyway.

**Comment by jrlevine** [comment]
Despite the nominal EOL dates, a lot of people still use old versions of python. I agree that we should continue to support them as long as reasonable, and not use spiffy new features just because they are new.

**Comment by jdufresne** [comment]
No problem.

I have limited this PR to only moving type annotations inline to function definitions.

One limitation of Python 3.5 is that it does not support type annotations for local variables. So these remain instance remains as type comments int he code.

**Comment by jdufresne** [comment]
I think it would be best to land #105 so we can see the results of this change run on GHA.

**Comment by kjd** [comment]
I seem to have messed up the merge but this is now merged with master. I had to update `idna-data` to generate the in-line type hints in `ut46data.py`.

**Pull request closed without merging**
