### PR TITLE
optimize memory consumption of idnadata, take 2

### PR DESCRIPTION
**Pull request by slingamn**
This is very close to #22 (it has the same advantages in memory consumption and the same performance penalty), except that the integer lists are now stored in a file and read via `mmap`. This has the benefit of allowing multiple Python processes to share the memory.

### CODE REVIEW

**Comment by slingamn** [comment]
re. code size: `idnadata.py` and its .pyc are now negligible (17K and 14K). Also, never mind my complaints about the exotic alphabets: the most space-hungry alphabets are `Common` and `Han`, neither of which is eliminable. The archaeological alphabets are small change.

**Comment by kjd** [comment]
Thanks for the work and the proposal. The focus on developing the library has been on protocol correctness, not performance, so I appreciate you taking the time to analyze memory footprint and processing requirements.

Above and beyond the performance tradeoff, the proposed approach perhaps does raise some 'taste' questions in that it makes the logic more opaque. I think I am OK with that given the significant improvement with respect to memory.

I'll review the patch more closely in the coming days with a mind to merging it.

A side note (more for myself): The Unicode data in this patch has more scripts in it because it is pulling from Unicode 8.0, but the implementation is currently mapped to Unicode 6.3 per the IAB guidance (see issue #8). I've put out an enquiry to see if there is progress on settling this issue and whether it makes sense to rev to Unicode 8.0.

**Comment by adamchainz** [comment]
+1 This is neat, I just came here because I saw that `import idna` was taking some time on my app.

**Comment by slingamn** [comment]
Thanks!

I added a couple of minor changes. The `DISALLOWED` codepoints were not being read by the logic, so I removed them from the build. (It looks like anything that's not specifically `PVALID`, `CONTEXTJ`, or `CONTEXTO` is invalid, whether its nominal status is `UNASSIGNED` or `DISALLOWED`, so there's no need to keep track of the distinction?)

Also, scripts outside of the set `['Greek', 'Han', 'Hebrew', 'Hiragana', 'Katakana']` are not special-cased by any RFC 5892 rules and don't need to be tracked, so I removed those as well.

Combined, these changes reduce the size of `idnadata.dat` from 1.5 MB to 700 KB (most of that was the `DISALLOWED` codepoints). Anyway, all data rebuilds are separate commits, so it should be easy to rebase them out and do your own rebuild, pending the outcome of the 6.3 vs. 8.0 question.

**Comment by kjd** [comment]
Superseded by #24

**Pull request closed without merging**
