### PR TITLE
Remove unnecessary numeric indexes in format strings

### PR DESCRIPTION
**Pull request by jdufresne**
Unnecessary since Python 2.7. Found using pyupgrade.

https://github.com/asottile/pyupgrade

### CODE REVIEW

**Comment by jribbens** [comment]
This would break Python 2.6 compatibility for no benefit.

**Comment by jdufresne** [comment]
According to setup.py, Python 2.6 isn't supported:

https://github.com/kjd/idna/blob/032fc55d5a39c2a916ec9e9334b00ba2bf40c5c4/setup.py#L16-L17

**Comment by jribbens** [comment]
You're not wrong, but nevertheless I believe it does currently work on Python 2.6 and breaking that for no benefit at all seems unnecessary.

**Comment by jayaddison** [comment]
@jdufresne @kjd There might be a few more examples of this that could be cleaned up in `idna/idna-data` (likely slipped through the net due to the absence of a `.py` extension):

- https://github.com/kjd/idna/blob/2b1633645ee776ff0642e3268d68a27c5b1c3f31/tools/idna-data#L530
- https://github.com/kjd/idna/blob/2b1633645ee776ff0642e3268d68a27c5b1c3f31/tools/idna-data#L570
- https://github.com/kjd/idna/blob/2b1633645ee776ff0642e3268d68a27c5b1c3f31/tools/idna-data#L572

**Pull request merged**
